// src/CatBreedsDetector.Client/src/components/Footer.tsx
import React from "react";
import "../styles/footer.css";

export default class Footer extends React.Component {
  public render(): JSX.Element {
    return (
      <footer id="footer" className="container text-center">
        <hr />
        Copyright &copy; Cat Breeds Detector, developed by YA Software
      </footer>
    );
  }
}

// CatBreedsDetector/CatBreedsDetector.Web/clientapp/src/components/Footer.vue
﻿<template>
    <footer id="footer" class="container text-center">
        <hr />
        Copyright &copy; Cat Breeds Detector, developed by YA Studios
    </footer>
</template>

<style scoped>
    #footer {
        padding-top: 10px;
        padding-bottom: 10px;
        position: fixed;
        bottom: 0;
        width: 100%;
    }
</style>
